#pragma once

enum class Texture : int
{
    MenuBack_Cartoon,
    Metal_Cartoon,
    Stone_Cartoon,
    Grass_Cartoon,
    Brick_Cartoon,
    Player_Cartoon,
    Enemy1_Cartoon,
    Enemy2_Cartoon,
    Enemy3_Cartoon,
    Bomb_Cartoon,
    Explosion_Cartoon,
    Door_Cartoon ,
    MenuBack_Clasico,
    Metal_Clasico,
    Stone_Clasico,
    Grass_Clasico,
    Brick_Clasico,
    Player_Clasico,
    Enemy1_Clasico,
    Enemy2_Clasico,
    Enemy3_Clasico,
    Bomb_Clasico,
    Explosion_Clasico,
    Door_Clasico,
    MenuBack_Personalizado,
    Metal_Personalizado,
    Stone_Personalizado,
    Grass_Personalizado,
    Brick_Personalizado,
    Player_Personalizado,
    Enemy1_Personalizado,
    Enemy2_Personalizado,
    Enemy3_Personalizado,
    Bomb_Personalizado,
    Explosion_Personalizado,
    Door_Personalizado,
    MenuBack_Realista,
    Metal_Realista,
    Stone_Realista,
    Grass_Realista,
    Brick_Realista,
    Player_Realista,
    Enemy1_Realista,
    Enemy2_Realista,
    Enemy3_Realista,
    Bomb_Realista,
    Explosion_Realista,
    Door_Realista,

};



